getVersOnOmnicomm/urls.py
from django.contrib import admin
from django.urls import path
from core import views
from django.views.generic import RedirectView

urlpatterns = [
    path('software_vis/admin/', admin.site.urls),
    path('software_vis/', views.filtredTableView, name='tractor-list'),
    path('software_vis/software_create/', views.SoftwareVersionCreateView.as_view(),
         name='software-create'),
    path('software_vis/component_create/', views.ComponentCreateView.as_view(),
         name='component-create'),
]

core/models.py
from django.db import models
from datetime import datetime

# Все уникальные поля, а также поля связей - индексируются Django по умолчанию


class Tractor(models.Model):
    id = models.IntegerField(primary_key=True, null=False,
                             verbose_name="ID in Omnicomm")
    serial_number = models.CharField(
        max_length=50, unique=True, verbose_name="Серийный номер"
    )
    name = models.CharField(max_length=100, verbose_name="Название")
    # through - ссылка на промежуточную модель, которая обсепечивает связь Many2Many
    components = models.ManyToManyField(
        "Component", verbose_name="Компоненты", related_name="tractors", through="Assembly", through_fields=('tractor', 'component')
    )
    software_versions = models.ManyToManyField(
        "SoftwareVersion", verbose_name='Версии прошивок', related_name="tractors", through="Assembly", through_fields=('tractor', 'software_version')
    )

    def __str__(self):
        return f"{self.name} ({self.serial_number})"

    class Meta:
        indexes = [
            models.Index(fields=['name'])
        ]


class Component(models.Model):
    NAMES_CHOICES = [
        ('EN', 'ДВС'),
        ('TB', 'Коробка передач'),
        ('SC', 'Рулевая колонка'),
        ('HD', 'Гидрораспределитель'),
        ('DP', 'Дисплей'),
        ('CN', 'Контроллер'),
    ]
    designation = models.CharField(max_length=100, unique=True,
                                   verbose_name="Обозначение узла")
    verbose_name = models.CharField(
        max_length=2, choices=NAMES_CHOICES, unique=False, verbose_name="Узел")

    def __str__(self):
        return self.designation

    class Meta:
        indexes = [
            models.Index(fields=['verbose_name'])
        ]


class SoftwareVersion(models.Model):
    component = models.ForeignKey(
        Component, on_delete=models.CASCADE, verbose_name="Узел", related_name="versions")
    # Полнотекстовое обозначение ПО
    version = models.CharField(
        max_length=50, verbose_name="Обозначение ПО", blank=True, null=True
    )
    # Обозначене ПО
    tractor_model = models.CharField(
        max_length=3, verbose_name="Модель трактора", blank=True, null=True
    )
    engine_comp = models.CharField(
        max_length=3, verbose_name="Производитель ДВС", blank=True, null=True
    )
    first_number = models.PositiveSmallIntegerField(
        verbose_name="Первые цифры в названии прошивки", blank=True, null=True
    )
    second_number = models.PositiveSmallIntegerField(
        verbose_name="Вторые цифры в названии прошивки", blank=True, null=True
    )
    third_number = models.PositiveSmallIntegerField(
        verbose_name="Третие цифры в названии прошивки", blank=True, null=True
    )
    ### Вспомогательные поля ###
    # Примечание
    note = models.CharField(
        max_length=255, verbose_name="Примечание", blank=True, null=True
    )
    # Критическое обновление, все версии до него считаются неисправными
    is_critical = models.BooleanField(
        default=False, verbose_name="Критическое обновление"
    )
    # Неисправная версия
    is_broken = models.BooleanField(
        default=False, verbose_name="Неисправная версия",
    )
    # Дата выпуска ПО
    release_date = models.DateField(
        verbose_name="Дата выпуска", null=True, blank=True, default=datetime.now
    )

    class Meta:
        ordering = ['-release_date', '-version']
        constraints = [models.UniqueConstraint(
            fields=['tractor_model', 'engine_comp', 'first_number', 'second_number', 'third_number'], name='unique_version')
        ]


    def __str__(self):
        return f"{self.component.designation}: {self.version}"

class Assembly(models.Model):  # Подумать над названием
    tractor = models.ForeignKey(
        Tractor, on_delete=models.CASCADE, verbose_name="Трактор", related_name="assamblies")
    component = models.ForeignKey(
        Component, on_delete=models.CASCADE, verbose_name="Узел", related_name="assamblies")
    software_version = models.ForeignKey(
        SoftwareVersion, on_delete=models.CASCADE, verbose_name="Нынешняя версия прошивки", related_name="assamblies")

    class Meta:
        verbose_name = "Сборка"
        verbose_name_plural = "Сборки"
        constraints = [
            models.UniqueConstraint(
                fields=["tractor", "component", "software_version"], name="unique_assembly")
        ]


# class Telemetry(models.Model):
#     tractor = models.ForeignKey(
#         Tractor, on_delete=models.CASCADE, verbose_name="Трактор")
#     component = models.ForeignKey(
#         Component, on_delete=models.CASCADE, verbose_name="Узел")
#     installed_version = models.CharField(
#         max_length=20, verbose_name="Установленная версия")
#     timestamp = models.DateTimeField(
#         auto_now_add=True, verbose_name="Время получения")

#     class Meta:
#         ordering = ['-timestamp']
#         indexes = [
#             models.Index(fields=['tractor', 'component']),
#         ]

#     def __str__(self):
#         return f"{self.tractor} - {self.component}: {self.installed_version}"

core/forms.py
from django import forms
from .models import SoftwareVersion, Component
from django.core.exceptions import ValidationError


class SoftwareVersionForm(forms.ModelForm):
    # Заменяем чекбокс на выпадающий список
    is_critical = forms.ChoiceField(
        choices=[(False, 'Minor'), (True, 'Major (Критическое обновление)')],
        label="Критическое обновление",
        widget=forms.Select(attrs={'class': 'form-control'}),
        initial='Minor'
    )

    class Meta:
        model = SoftwareVersion
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.pk:
            self.initial['is_critical'] = self.instance.is_critical
        self.fields['is_broken'].widget = forms.HiddenInput()

    def clean(self):
        cleaned_data = super().clean()
        version = cleaned_data.get('version')

        if version:
            parts = version.split('.')
            if len(parts) == 5:
                try:
                    cleaned_data['tractor_model'] = parts[0]
                    cleaned_data['engine_comp'] = parts[1]
                    cleaned_data['first_number'] = int(parts[2])
                    cleaned_data['second_number'] = int(parts[3])
                    cleaned_data['third_number'] = int(parts[4])
                except:
                    pass
        elif cleaned_data.get('tractor_model') and cleaned_data.get('engine_comp') and cleaned_data.get('first_number') and cleaned_data.get('second_number') and cleaned_data.get('third_number'):
            cleaned_data['version'] = f"{cleaned_data.get('tractor_model')}.{cleaned_data.get('engine_comp')}.{cleaned_data.get('first_number')}.{cleaned_data.get('second_number')}.{cleaned_data.get('third_number')}"
        else:
            raise ValidationError(
                f'Должно быть заполнено либо поле "Обозначение ПО", либо все остальные поля, кроме даты выпуска')
        return cleaned_data


class ComponentForm(forms.ModelForm):
    class Meta:
        model = Component
        fields = '__all__'


class StatusForm(forms.Form):
    status = forms.ChoiceField(
        choices=[(0, 'Все'), (2, 'Критически устаревшие трактора (major)'),
                 (3, 'Не критически устаревшие трактора(minor)')],
        label='Статус трактора',
        initial='Все'
    )

core/views.py
from django.shortcuts import render
from django.db.models import Subquery, OuterRef
from django.views.generic.edit import CreateView

from .forms import SoftwareVersionForm, ComponentForm, StatusForm
from .models import Tractor, Component, SoftwareVersion, Assembly

def search_status_versions(tractors):
    tractors_info = []
    NAMES_CHOICES = ['EN', 'TB', 'SC', 'HD', 'DP', 'CN']
    for eachTractor in tractors:
        tractor_status = 'green'
        components_info = [{'name': '—', 'designation_comp': '—',
                            'version': '—', 'status': 'gray'}]*6
        for eachVersion in eachTractor.software_versions.all():
            if eachVersion.tractor_model is None:
                thisversions = SoftwareVersion.objects.filter(
                    component__designation = eachVersion.component.designation).order_by('-version')
                status = 'gray'
                if eachVersion.version == thisversions.first().version:
                    status = 'green'
                else:
                    for otherVersion in thisversions:
                        if otherVersion.version == eachVersion.version:
                            status = 'old'
                            if tractor_status != 'critical_old':
                                tractor_status = 'old'
                            break
                        if otherVersion.is_critical:
                            status = 'critical_old'
                            tractor_status = 'critical_old'
                            break
            else:
                thisversions = SoftwareVersion.objects.filter(tractor_model=eachVersion.tractor_model, engine_comp=eachVersion.engine_comp,
                                                              first_number=eachVersion.first_number).order_by('-release_date')
                status = 'green'
                for otherVersion in thisversions:
                    if otherVersion.second_number == eachVersion.second_number and otherVersion.third_number > eachVersion.third_number:
                        if otherVersion.is_critical:
                            status = 'critical_old'
                            tractor_status = 'critical_old'
                            break
                        else:
                            if tractor_status != 'critical_old':
                                tractor_status = 'old'
                            status = 'old'
                    if otherVersion.second_number > eachVersion.second_number:
                        if otherVersion.is_critical:
                            status = 'critical_old'
                            tractor_status = 'critical_old'
                            break
                        else:
                            if tractor_status != 'critical_old':
                                tractor_status = 'old'
                            status = 'old'
            if eachVersion.is_broken:
                status = 'broken'
                tractor_status = 'broken'
            components_info[NAMES_CHOICES.index(eachVersion.component.verbose_name)] = {'name': eachVersion.component.verbose_name, 'designation_comp': eachVersion.component.designation,
                                                                                        'version': eachVersion.version, 'status': status}
        tractors_info.append({'id': eachTractor.id, 'serial_number': eachTractor.serial_number,
                             'name': eachTractor.name, 'components': components_info, 'tractor_status': tractor_status})
    return tractors_info


def filtredTableView(request):
    if request.method == 'POST':
        form = StatusForm(request.POST)
        tractors = []
        if form.is_valid():
            if form.cleaned_data['status'] == '0':
                tractors = search_status_versions(Tractor.objects.all())
            elif form.cleaned_data['status'] == '1':
                tractors = search_status_versions(Tractor.objects.filter(
                    software_versions__is_broken=True))
            elif form.cleaned_data['status'] == '2':
                tractors = list(filter(
                    lambda x: x['tractor_status'] == 'critical_old' or x['tractor_status'] == 'broken', search_status_versions(Tractor.objects.all())))
            elif form.cleaned_data['status'] == '3':
                tractors = list(
                    filter(lambda x: x['tractor_status'] == 'old', search_status_versions(Tractor.objects.all())))
        context = {'tractors_info': tractors,
                   'form': form}
        return render(request, 'core/tractors.html', context=context)
    else:
        form = StatusForm()
        tractors = search_status_versions(Tractor.objects.all())
        context = {'tractors_info': tractors,
                   'form': form}
        return render(request, 'core/tractors.html', context=context)


class SoftwareVersionCreateView(CreateView):
    model = SoftwareVersion
    form_class = SoftwareVersionForm
    template_name = 'core/software_version_create_form.html'
    success_url = '/software_vis/software_create/'

    def form_valid(self, form):
        form.instance.is_critical = (
            form.cleaned_data['is_critical'] == 'True')
        return super().form_valid(form)


class ComponentCreateView(CreateView):
    models = Component
    form_class = ComponentForm
    template_name = 'core/component_create_form.html'
    success_url = '/software_vis/component_create/'

    

core/templates/core/component_create_form.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Состояние ПО тракторов</title>
    <link rel="stylesheet" href="{% static 'css/cell_colors.css' %}">
    <style>
        .scrollable {
            overflow-x: auto;
        }
    </style>
</head>
<body>
    <ol itemscope itemtype="https://schema.org/BreadcrumbList">
        <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
            <a itemprop="item" href="{% url 'tractor-list' %}">
            <span itemprop="name">Список тракторов</span>
            </a>
            <meta itemprop="position" content="1" />
        </li>
        <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
            {% comment %} <a itemprop="item" href="{% url 'component-create' %}"> {% endcomment %}
            <span itemprop="name">Добавление узла</span>
            {% comment %} </a> {% endcomment %}
            <meta itemprop="position" content="2" />
        </li>
        <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
            <a itemprop="item" href="{% url 'software-create' %}">
            <span itemprop="name">Добавление версии ПО</span>
            </a>
            <meta itemprop="position" content="3" />
        </li>
    </ol>
    <h1>Добавление узла</h1>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
</body>
</html>

core/templates/core/software_version_create_form.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Состояние ПО тракторов</title>
    <link rel="stylesheet" href="{% static 'css/cell_colors.css' %}">
    <style>
        .scrollable {
            overflow-x: auto;
        }
    </style>
</head>
<body>
    <ol itemscope itemtype="https://schema.org/BreadcrumbList">
        <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
            <a itemprop="item" href="{% url 'tractor-list' %}">
            <span itemprop="name">Список тракторов</span>
            </a>
            <meta itemprop="position" content="1" />
        </li>
        <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
            <a itemprop="item" href="{% url 'component-create' %}">
            <span itemprop="name">Добавление узла</span>
            </a>
            <meta itemprop="position" content="2" />
        </li>
        <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
            <span itemprop="name">Добавление версии ПО</span>
            <meta itemprop="position" content="3" />
        </li>
    </ol>
    <h1>Добавление версии ПО</h1>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
</body>
</html>

core/templates/core/tractors.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Состояние ПО тракторов</title>
    <link rel="stylesheet" href="{% static 'css/cell_colors.css' %}">
    <style>
        table { border-collapse: collapse; width: 100%; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; text-align: center;}
        th { background-color: #f2f2f2; text-align: center;}
        .scrollable {
            overflow-x: auto;
        }
    </style>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>
</head>
<body>
    {{ tractors_info|json_script:"tractors_info_response" }}
    {{ components|json_script:"components_response" }}
    <ol itemscope itemtype="https://schema.org/BreadcrumbList">
        <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
            <span itemprop="name">Список тракторов</span>
            <meta itemprop="position" content="1" />
        </li>
        <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
            <a itemprop="item" href="{% url 'component-create' %}">
            <span itemprop="name">Добавление узла</span>
            </a>
            <meta itemprop="position" content="2" />
        </li>
        <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
            <a itemprop="item" href="{% url 'software-create' %}">
            <span itemprop="name">Добавление версии ПО</span>
            </a>
            <meta itemprop="position" content="3" />
        </li>
    </ol>
    <form method="post">
        {% csrf_token %}
        <div>
        {{ form.status }}
        <script>
            document.addEventListener('DOMContentLoaded', function() {
                const select = document.querySelector('#id_status');
                if (select) {
                    select.addEventListener('change', function() {
                        this.form.submit();
                    });
                }
            });
        </script>
        </div>
    </form>
    <h1>Версии ПО тракторов</h1>
    <ul class="des-ul">
        <li class="des-li">
            <div class="color-block green"></div>
            <span>Актуальная версия</span>
        </li>
        <li class="des-li">
            <div class="color-block old"></div>
            <span>Устаревшая версия</span>
        </li>
        <li class="des-li">
            <div class="color-block critical_old"></div>
            <span>Критически устаревшая версия</span>
        </li>
    </ul>
    <table class="tractor_list_table", id="tractor_list_table">
        <thead>
            <tr>
                <th rowspan="3" scope="col">№ Трактора</th>
                <th rowspan="3" scope="col">Модель трактора</th>
                <th colspan="2" rowspan="2" scope="col">ДВС</th>
                <th colspan="2" rowspan="2" scope="col">КП</th>
                <th colspan="2" rowspan="2" scope="col">Рулевая колонка</th>
                <th colspan="2" rowspan="2" scope="col">Распред</th>
                <th colspan="4" scope="col">БК</th>
            </tr>
            <tr>
                <th colspan="2" scope="col">Дисплей БК</th>
                <th colspan="2" scope="col">Контроллер БК</th>
            </tr>
            <tr>
                <th scope="col">Артикул</th>
                <th scope="col">Версия ПО</th>
                <th scope="col">Артикул</th>
                <th scope="col">Версия ПО</th>
                <th scope="col">Артикул</th>
                <th scope="col">Версия ПО</th>
                <th scope="col">Артикул</th>
                <th scope="col">Версия ПО</th>
                <th scope="col">Артикул</th>
                <th scope="col">Версия ПО</th>
                <th scope="col">Артикул</th>
                <th scope="col">Версия ПО</th>
            </tr>
        </thead>
        <tbody class="tractor_list_tbody">
        </tbody>
    </table>
    <script src="{% static 'js/tractor_list.js' %}"></script>
    <script>
        $(document).ready(function() {
            // Плагин сортировки по цвету
            $.fn.dataTable.ext.type.order['color-pre'] = function(d) {
                switch (d) {
                    case 'broken': return 1;
                    case 'crirtical_old': return 2;
                    case 'old': return 3;
                    case 'green': return 4;
                    default: return 5;
                }
            };
            // Инициализация DataTable с пользовательской сортировкой
            var table = $('#tractor_list_table').DataTable({
                "pageLength": 10,
                "ordering": true,
                "searching": true,
            });
            // Добавляем выпадающий список для фильтрации по цвету
            {% comment %} $('.dataTables_filter').before(
                '<div class="color-filter" style="margin-bottom: 10px;">' +
                    '<label>Фильтр по цвету: </label>' +
                    '<select id="colorFilter">' +
                        '<option value="all">Все цвета</option>' +
                        '<option value="broken">Неисправные версии</option>' +
                        '<option value="crirtical_old">До major`ные версии</option>' +
                        '<option value="old">minor-устаревшие версии</option>' +
                        '<option value="green">Зелёные</option>' +
                    '</select>' +
                '</div>'
            );
            // Обработчик для фильтрации по цвету
            $('#colorFilter').on('change', function() {
                var color = this.value;
                if (color) {
                    // Ищем ячейки с указанным цветом
                    $.fn.dataTable.ext.search.push(function(settings, data, dataIndex) {
                        if (color == 'all'){
                            console.log(color)
                        }
                        var row = table.row(dataIndex).node();
                        var hasColor = ($(row).find('td[data-color="' + color + '"]').length > 0);
                        return hasColor;
                    });
                } else {
                    // Сбрасываем фильтр
                    $.fn.dataTable.ext.search.pop();
                }
                
                table.draw();
            });
            $.fn.dataTable.ext.search.push(function(settings, data, dataIndex) {
                var searchTerm = table.search().toLowerCase();
                var row = table.row(dataIndex).node();
                console.log(searchTerm);

                if (searchTerm == 'неисправные' || searchTerm == 'broken') {
                    return $(row).find('data-color="broken"').length > 0;
                }
                if (searchTerm == 'критически устаревшие' || searchTerm == 'crirtical old' || searchTerm == 'major') {
                    return $(row).find('data-color="crirtical_old"').length > 0;
                }
                if (searchTerm == 'устаревшие' || searchTerm == 'old' || searchTerm == 'minor') {
                    return $(row).find('data-color="old"').length > 0;
                }
                if (searchTerm == 'зелёные' || searchTerm == 'green' || searchTerm == 'зеленые') {
                    return $(row).find('data-color="green"').length > 0;
                }
                
                return true;
            });
            table.draw();{% endcomment %}
        });
    </script>
</body>
</html>